language: php

env:
  global:
    - setup=stable

matrix:
  fast_finish: true
  include:
    - php: 7.3
      env: COVERAGE=1
    - php: 7.2
      env: COVERAGE=0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

install:
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi

script:
  - if [ "$COVERAGE" == "1" ]; then vendor/bin/phpunit --coverage-clover=coverage.xml; fi
  - if [ "$COVERAGE" == "0" ]; then vendor/bin/phpunit; fi

after_success:
    - bash <(curl -s https://codecov.io/bash)
