on: push
name: tests
jobs:
  linux_tests:
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    strategy:
      fail-fast: true
      matrix:
        php: ['8.0']
        stability: [prefer-lowest, prefer-stable]

    name: PHP ${{ matrix.php }} - ${{ matrix.stability }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pcov
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: pcov

      - name: Install dependencies
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress

      - name: Execute tests
        run: vendor/bin/phpunit --verbose --coverage-clover './clover.xml'

      - name: Upload coverage to Codecov
        if: ${{ matrix.stability == 'prefer-stable' }}
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: .
          fail_ci_if_error: true
          files: ./clover.xml
          name: codecov-umbrella
          path_to_write_report: ./codecov_report.txt
          verbose: true

      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: ./codecov_report.txt

